### ISSUE TITLE
Values without electrode connected

### ISSUE THREAD

**Issue by gerardklee** [neurosity/eeg-pipes#40]
Hi,

First of all, thank you for the awesome library! This provides just exactly what I want. 
I am trying to interpret the values from the eeg-pipes library and the OpenBCI. What I am trying to do is to build a neurofeedback system that specifically targets alpha waves. 

When I tried this library without connecting any electrode on my head, I could see some values on my terminal. Is it safe to consider those values as noise values? Attached is the screenshot of the terminal and my code. Thanks for help!

<img width="227" alt="Screen Shot 2020-02-05 at 2 04 14 PM" src="https://user-images.githubusercontent.com/47463934/73887626-c6390380-4820-11ea-8fa1-575b24621921.png">
<img width="508" alt="Screen Shot 2020-02-05 at 2 06 50 PM" src="https://user-images.githubusercontent.com/47463934/73887629-c802c700-4820-11ea-888a-7a24179c2b82.png">

**Comment by jdpigeon** [comment]
Yep. Those values are going to be the per-band frequency components of whatever signal is going through the EEG electrodes when it's not on your head. Not very useful, but at least an indication that you've got all the software hooked up right and data is flowing!
