### ISSUE TITLE
What type of window does eeg-pipes use? Hanning

### ISSUE THREAD

**Issue by apavlo89** [neurosity/eeg-pipes#53]
What type of window does eeg-pipes use? Does it use Hanning for example?

**Comment by apavlo89** [comment]
For example there are these types of windows

What type of window does muse js use?

For example there are these windows

Window types:

boxcar

triang

blackman

hamming

hann

bartlett

flattop

parzen

bohman

blackmanharris

nuttall

barthann

kaiser (needs beta)

gaussian (needs standard deviation)

general_gaussian (needs power, width)

slepian (needs width)

dpss (needs normalized half-bandwidth)

chebwin (needs attenuation)

exponential (needs decay scale)

tukey (needs taper fraction)

**Comment by apavlo89** [comment]
Anybody home?

**Comment by alexcastillo** [comment]
Hi @apavlo89,

What specific pipe are you referring to?

**Comment by yannickadam** [comment]
@apavlo89 It looks like there is no available pipe to apply a window function
@alexcastillo PR #58 created if you'd like.

**Comment by alexcastillo** [comment]
Thank you so much, @yannickadam!

**Comment by alexcastillo** [comment]
PR merged.
