### ISSUE TITLE
Clarification of Epoch interval parameter

### ISSUE THREAD

**Issue by yannickadam** [neurosity/eeg-pipes#56]
Hi, and thanks for this library!

Looking at the doc for Epoch, it is mentioned: 
``* @param {number} [options.interval=100] Time (ms) between emitted Epochs``

However, a ``bufferCount(interval)`` is used to accumulate the samples. To really emit every 100ms, in the case of a sampling rate of 256Hz, an interval of ~26 would be needed.

Could you confirm?

**Comment by alexcastillo** [comment]
Hey @yannickadam,

Thank you so much for all of your contributions!

As per your question, yes, that's exactly correct.

We actually use an interval of `25` in Neurosity OS (which uses eeg-pipes on embedded hardware) for our Notion EEG device.
